# Generated by Django 5.2.7 on 2025-11-25 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='RestricaoFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, help_text='Motivo da incompatibilidade', max_length=200, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('familia_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricoes_como_origem', to='logistics.familia', verbose_name='Família de Origem')),
                ('familia_restrita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricoes_como_destino', to='logistics.familia', verbose_name='Família Incompatível')),
            ],
            options={
                'verbose_name': 'Restrição de Família',
                'verbose_name_plural': 'Restrições de Famílias',
                'ordering': ['familia_origem__nome'],
                'unique_together': {('familia_origem', 'familia_restrita')},
            },
        ),
    ]
