# Generated by Django 5.2.8 on 2025-12-05 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_pedido_campos_endereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familia',
            options={'verbose_name': 'Familia', 'verbose_name_plural': 'Familias'},
        ),
        migrations.AlterModelOptions(
            name='restricaofamilia',
            options={'ordering': ['familia_origem__nome'], 'verbose_name': 'Restricao de Familia', 'verbose_name_plural': 'Restricoes de Familias'},
        ),
        migrations.AlterField(
            model_name='restricaofamilia',
            name='familia_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricoes_como_origem', to='logistics.familia', verbose_name='Familia de Origem'),
        ),
        migrations.AlterField(
            model_name='restricaofamilia',
            name='familia_restrita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricoes_como_destino', to='logistics.familia', verbose_name='Familia Incompativel'),
        ),
        migrations.AlterField(
            model_name='rota',
            name='capacidade_max',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Capacidade Maxima'),
        ),
        migrations.AlterField(
            model_name='rota',
            name='status',
            field=models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_EXECUCAO', 'Em execucao'), ('CONCLUIDA', 'Concluida')], default='PLANEJADA', max_length=20),
        ),
    ]
