# Generated by Django 5.2.8 on 2025-12-07 20:31

import django.db.models.deletion
from django.db import migrations, models


def preencher_chave_bidirecional(apps, schema_editor):
    Restricao = apps.get_model("logistics", "RestricaoFamilia")
    for restricao in Restricao.objects.all():
        ids = sorted([restricao.familia_origem_id, restricao.familia_restrita_id])
        restricao.chave_bidirecional = f"{ids[0]}:{ids[1]}"
        restricao.save(update_fields=["chave_bidirecional"])


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_familia_options_alter_restricaofamilia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoRestricaoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo do Pedido',
                'verbose_name_plural': 'Grupos de Pedidos',
                'ordering': ['pedido_id', 'titulo'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='restricaofamilia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='restricaofamilia',
            name='chave_bidirecional',
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.RunPython(preencher_chave_bidirecional, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='restricaofamilia',
            constraint=models.UniqueConstraint(fields=('chave_bidirecional',), name='uniq_restricao_familia_bidirecional'),
        ),
        migrations.AddField(
            model_name='pedidorestricaogrupo',
            name='familias',
            field=models.ManyToManyField(blank=True, related_name='grupos_restricao', to='logistics.familia'),
        ),
        migrations.AddField(
            model_name='pedidorestricaogrupo',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_restricao', to='logistics.pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='rotapedido',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='produtopedido',
            name='grupo_restricao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='logistics.pedidorestricaogrupo'),
        ),
        migrations.AddField(
            model_name='rotapedido',
            name='grupo_restricao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotas', to='logistics.pedidorestricaogrupo'),
        ),
        migrations.AlterUniqueTogether(
            name='rotapedido',
            unique_together={('rota', 'pedido', 'grupo_restricao')},
        ),
    ]
